[package]
name = "gdlk_cli"
version = "0.1.0"
authors = [
    "John Reilly Murray <johnreillymurray@gmail.com>",
    "Lucas Pickering <lucas@lucaspickering.me>",
]
edition = "2018"

[dependencies]
failure = "0.1"
gdlk = { path = "../lib" }
structopt = "0.3"
